# Project: Census Income Prediction (>50K)
# Notebook: 01_data_validation.ipynb
# Author: Your Name
# Purpose: Data Quality Validation & Dataset Audit

## Dataset Loading Validation

The Adult Census dataset was successfully loaded.

- Training dataset (adult.data): 32,561 records
- Test dataset (adult.test): 16,281 records

The row counts match the official UCI Adult dataset documentation, indicating that the files were loaded correctly without data loss.

In [96]:
import pandas as pd
import numpy as np

In [97]:
adult_data = pd.read_csv("adult.data",header=None,skipinitialspace=True)
print("adult.data Shape:", adult_data.shape)
adult_data.head()

adult.data Shape: (32561, 15)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [98]:
adult_test = pd.read_csv("adult.test",header=None,skiprows=1,  # first row is metadata
    skipinitialspace=True
)
print("adult.test Shape:", adult_test.shape)
adult_test.head()

adult.test Shape: (16281, 15)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K.
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K.
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K.
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K.
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K.

In [99]:
with open("adult.names", "r") as f:
    adult_names = f.read()
print(adult_names)

| This data was extracted from the census bureau database found at
| http://www.census.gov/ftp/pub/DES/www/welcome.html
| Donor: Ronny Kohavi and Barry Becker,
|        Data Mining and Visualization
|        Silicon Graphics.
|        e-mail: ronnyk@sgi.com for questions.
| Split into train-test using MLC++ GenCVFiles (2/3, 1/3 random).
| 48842 instances, mix of continuous and discrete    (train=32561, test=16281)
| 45222 if instances with unknown values are removed (train=30162, test=15060)
| Duplicate or conflicting instances : 6
| Class probabilities for adult.all file
| Probability for the label '>50K'  : 23.93% / 24.78% (without unknowns)
| Probability for the label '<=50K' : 76.07% / 75.22% (without unknowns)
|
| Extraction was done by Barry Becker from the 1994 Census database.  A set of
|   reasonably clean records was extracted using the following conditions:
|   ((AAGE>16) && (AGI>100) && (AFNLWGT>1)&& (HRSWK>0))
|
| Prediction task is to determine whether a person makes over 50K
| a year.
|
| First cited in:
| @inproceedings{kohavi-nbtree,
|    author={Ron Kohavi},
|    title={Scaling Up the Accuracy of Naive-Bayes Classifiers: a
|           Decision-Tree Hybrid},
|    booktitle={Proceedings of the Second International Conference on
|               Knowledge Discovery and Data Mining},
|    year = 1996,
|    pages={to appear}}
|
| Error Accuracy reported as follows, after removal of unknowns from
|    train/test sets):
|    C4.5       : 84.46+-0.30
|    Naive-Bayes: 83.88+-0.30
|    NBTree     : 85.90+-0.28
|
|
| Following algorithms were later run with the following error rates,
|    all after removal of unknowns and using the original train/test split.
|    All these numbers are straight runs using MLC++ with default values.
|
|    Algorithm               Error
| -- ----------------        -----
| 1  C4.5                    15.54
| 2  C4.5-auto               14.46
| 3  C4.5 rules              14.94
| 4  Voted ID3 (0.6)         15.64
| 5  Voted ID3 (0.8)         16.47
| 6  T2                      16.84
| 7  1R                      19.54
| 8  NBTree                  14.10
| 9  CN2                     16.00
| 10 HOODG                   14.82
| 11 FSS Naive Bayes         14.05
| 12 IDTM (Decision table)   14.46
| 13 Naive-Bayes             16.12
| 14 Nearest-neighbor (1)    21.42
| 15 Nearest-neighbor (3)    20.35
| 16 OC1                     15.04
| 17 Pebls                   Crashed.  Unknown why (bounds WERE increased)
|
| Conversion of original data as follows:
| 1. Discretized agrossincome into two ranges with threshold 50,000.
| 2. Convert U.S. to US to avoid periods.
| 3. Convert Unknown to "?"
| 4. Run MLC++ GenCVFiles to generate data,test.
|
| Description of fnlwgt (final weight)
|
| The weights on the CPS files are controlled to independent estimates of the
| civilian noninstitutional population of the US.  These are prepared monthly
| for us by Population Division here at the Census Bureau.  We use 3 sets of
| controls.
|  These are:
|          1.  A single cell estimate of the population 16+ for each state.
|          2.  Controls for Hispanic Origin by age and sex.
|          3.  Controls by Race, age and sex.
|
| We use all three sets of controls in our weighting program and "rake" through
| them 6 times so that by the end we come back to all the controls we used.
|
| The term estimate refers to population totals derived from CPS by creating
| "weighted tallies" of any specified socio-economic characteristics of the
| population.
|
| People with similar demographic characteristics should have
| similar weights.  There is one important caveat to remember
| about this statement.  That is that since the CPS sample is
| actually a collection of 51 state samples, each with its own
| probability of selection, the statement only applies within
| state.


>50K, <=50K.

age: continuous.
workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
fnlwgt: continuous.
education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
education-num: continuous.
marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
sex: Female, Male.
capital-gain: continuous.
capital-loss: continuous.
hours-per-week: continuous.
native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.

In [100]:
with open("old.adult.names", "r") as f:
    old_adult_names = f.read()
print(old_adult_names)

1. Title of Database: adult
2. Sources:
   (a) Original owners of database (name/phone/snail address/email address)
       US Census Bureau.
   (b) Donor of database (name/phone/snail address/email address)
       Ronny Kohavi and Barry Becker,
       Data Mining and Visualization
       Silicon Graphics.
       e-mail: ronnyk@sgi.com
   (c) Date received (databases may change over time without name change!)
       05/19/96
3. Past Usage:
   (a) Complete reference of article where it was described/used
        @inproceedings{kohavi-nbtree,
           author={Ron Kohavi},
           title={Scaling Up the Accuracy of Naive-Bayes Classifiers: a
                  Decision-Tree Hybrid},
           booktitle={Proceedings of the Second International Conference on
                      Knowledge Discovery and Data Mining},
           year = 1996,
           pages={to appear}}
   (b) Indication of what attribute(s) were being predicted
       Salary greater or less than 50,000.
   (b) Indication of study's results (i.e. Is it a good domain to use?)
       Hard domain with a nice number of records.
       The following results obtained using MLC++ with default settings
       for the algorithms mentioned below.

           Algorithm               Error
        -- ----------------        -----
        1  C4.5                    15.54
        2  C4.5-auto               14.46
        3  C4.5 rules              14.94
        4  Voted ID3 (0.6)         15.64
        5  Voted ID3 (0.8)         16.47
        6  T2                      16.84
        7  1R                      19.54
        8  NBTree                  14.10
        9  CN2                     16.00
        10 HOODG                   14.82
        11 FSS Naive Bayes         14.05
        12 IDTM (Decision table)   14.46
        13 Naive-Bayes             16.12
        14 Nearest-neighbor (1)    21.42
        15 Nearest-neighbor (3)    20.35
        16 OC1                     15.04
        17 Pebls                   Crashed.  Unknown why (bounds WERE increased)

4. Relevant Information Paragraph:
   Extraction was done by Barry Becker from the 1994 Census database.  A set
    of reasonably clean records was extracted using the following conditions:
    ((AAGE>16) && (AGI>100) && (AFNLWGT>1)&& (HRSWK>0))

5. Number of Instances
   48842 instances, mix of continuous and discrete    (train=32561, test=16281)
   45222 if instances with unknown values are removed (train=30162, test=15060)
   Split into train-test using MLC++ GenCVFiles (2/3, 1/3 random).

6. Number of Attributes
   6 continuous, 8 nominal attributes.

7. Attribute Information:

age: continuous.
workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
fnlwgt: continuous.
education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
education-num: continuous.
marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
sex: Female, Male.
capital-gain: continuous.
capital-loss: continuous.
hours-per-week: continuous.
native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.
class: >50K, <=50K

8. Missing Attribute Values:

   7% have missing values.

9. Class Distribution:

 Probability for the label '>50K'  : 23.93% / 24.78% (without unknowns)
 Probability for the label '<=50K' : 76.07% / 75.22% (without unknowns)

In [101]:
with open("Index", "r") as f:
    index_file = f.read()
print(index_file)

Index of adult

02 Dec 1996      140 Index
10 Aug 1996  3974305 adult.data
10 Aug 1996     4267 adult.names
10 Aug 1996  2003153 adult.test

In [102]:
print("adult.data rows :", adult_data.shape)
print("adult.test rows :", adult_test.shape)

adult.data rows : (32561, 15)
adult.test rows : (16281, 15)

In [103]:
#coloumn names are already mentioned in the "adult.names" files
columns = [
    'age',
    'workclass',
    'fnlwgt',
    'education',
    'education_num',
    'marital_status',
    'occupation',
    'relationship',
    'race',
    'sex',
    'capital_gain',
    'capital_loss',
    'hours_per_week',
    'native_country',
    'income'
]
adult_data.columns = columns
adult_test.columns = columns

In [104]:
adult_data.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [105]:
adult_test.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K.
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K.
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K.
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K.
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K.

In [106]:
adult_data.sample(5)

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
5536,54,Local-gov,186884,Some-college,10,Married-civ-spouse,Transport-moving,Husband,Black,Male,0,0,30,United-States,<=50K
10433,27,Private,207611,HS-grad,9,Never-married,Other-service,Not-in-family,White,Female,0,0,52,United-States,<=50K
20882,54,Private,256916,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,<=50K
29580,27,Private,178688,Assoc-voc,11,Never-married,Craft-repair,Other-relative,White,Male,0,0,40,United-States,<=50K
32461,24,Private,284317,Bachelors,13,Never-married,Machine-op-inspct,Not-in-family,White,Female,0,0,32,United-States,<=50K

In [107]:
adult_test.sample(5)

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
327,18,Private,161245,11th,7,Never-married,Other-service,Own-child,White,Male,0,0,15,United-States,<=50K.
2917,42,Private,202083,Assoc-voc,11,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,Canada,<=50K.
4021,64,Self-emp-inc,56588,Some-college,10,Widowed,Exec-managerial,Unmarried,White,Female,0,0,70,United-States,<=50K.
15500,22,Federal-gov,277700,Some-college,10,Never-married,Tech-support,Own-child,White,Male,0,0,20,United-States,<=50K.
2561,25,State-gov,203279,Bachelors,13,Never-married,Prof-specialty,Not-in-family,Asian-Pac-Islander,Male,0,0,20,India,<=50K.

In [108]:
print("Shape:", adult_data.shape)
print("Rows:", adult_data.shape[0])
print("Columns:", adult_data.shape[1])
adult_data.columns

Shape: (32561, 15)
Rows: 32561
Columns: 15

Index(['age', 'workclass', 'fnlwgt', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'race', 'sex',
       'capital_gain', 'capital_loss', 'hours_per_week', 'native_country',
       'income'],
      dtype='object')

In [109]:
print("Shape:", adult_test.shape)
print("Rows:", adult_test.shape[0])
print("Columns:", adult_test.shape[1])
adult_test.columns

Shape: (16281, 15)
Rows: 16281
Columns: 15

Index(['age', 'workclass', 'fnlwgt', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'race', 'sex',
       'capital_gain', 'capital_loss', 'hours_per_week', 'native_country',
       'income'],
      dtype='object')

In [110]:
adult_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [111]:
adult_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16281 entries, 0 to 16280
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             16281 non-null  int64
 1   workclass       16281 non-null  object
 2   fnlwgt          16281 non-null  int64
 3   education       16281 non-null  object
 4   education_num   16281 non-null  int64
 5   marital_status  16281 non-null  object
 6   occupation      16281 non-null  object
 7   relationship    16281 non-null  object
 8   race            16281 non-null  object
 9   sex             16281 non-null  object
 10  capital_gain    16281 non-null  int64
 11  capital_loss    16281 non-null  int64
 12  hours_per_week  16281 non-null  int64
 13  native_country  16281 non-null  object
 14  income          16281 non-null  object
dtypes: int64(6), object(9)
memory usage: 1.9+ MB

In [112]:
for col in adult_data.columns:
    print(col, (adult_data[col] == '?').sum())

age 0
workclass 1836
fnlwgt 0
education 0
education_num 0
marital_status 0
occupation 1843
relationship 0
race 0
sex 0
capital_gain 0
capital_loss 0
hours_per_week 0
native_country 583
income 0

In [113]:
for col in adult_test.columns:
    print(col, (adult_test[col] == '?').sum())

age 0
workclass 963
fnlwgt 0
education 0
education_num 0
marital_status 0
occupation 966
relationship 0
race 0
sex 0
capital_gain 0
capital_loss 0
hours_per_week 0
native_country 274
income 0

### Missing Value Findings

Missing values are represented by the '?' character rather than null values.

The following columns contain missing values:

- workclass
- occupation
- native_country

Occupation has the highest missingness, followed by workclass and native_country.

Missing values are present in both training and test datasets and will be handled during preprocessing (Notebook 3).

In [114]:
missing_train = pd.DataFrame({'Missing Count': (adult_data == '?').sum()})
missing_train['Missing %'] = round((missing_train['Missing Count'] / len(adult_data)) * 100,2)
missing_train = missing_train.sort_values(by='Missing Count',ascending=False)
missing_train[missing_train['Missing Count'] > 0]

                Missing Count  Missing %
occupation               1843       5.66
workclass                1836       5.64
native_country            583       1.79

In [115]:
missing_test = pd.DataFrame({'Missing Count': (adult_test == '?').sum()})
missing_test['Missing %'] = round((missing_test['Missing Count'] / len(adult_test)) * 100,2)
missing_test = missing_test.sort_values(by='Missing Count',ascending=False)
missing_test[missing_test['Missing Count']>0]

                Missing Count  Missing %
occupation                966       5.93
workclass                 963       5.91
native_country            274       1.68

### Duplicate Record Findings

A duplicate record check was performed on both datasets.

Results:
- Training Dataset: 24 duplicate records (0.07%)
- Test Dataset: 5 duplicate records (0.03%)

The duplicate rate is very low in both datasets. A decision regarding duplicate removal will be documented in the preprocessing policy notebook.

In [116]:
print("Train Duplicates:", adult_data.duplicated().sum())
print("Test Duplicates :", adult_test.duplicated().sum())

Train Duplicates: 24
Test Duplicates : 5

In [117]:
train_dup = round(adult_data.duplicated().sum() / len(adult_data) * 100,2)
test_dup = round(adult_test.duplicated().sum() / len(adult_test) * 100,2)
print("Train Duplicate %:", train_dup)
print("Test Duplicate % :", test_dup)

Train Duplicate %: 0.07
Test Duplicate % : 0.03

### Target Variable Validation

The income target variable contains two classes:

Training Dataset:
- <=50K
- >50K

Test Dataset:
- <=50K.
- >50K.


The class distribution is very similar between the train and test datasets.

Approximately 76% of observations belong to the <=50K class,
while approximately 24% belong to the >50K class.

The dataset is moderately imbalanced but not severely imbalanced.

In [121]:
income_dist_train = pd.DataFrame({'Count': adult_data['income'].value_counts(),
                                  'Percentage': round(adult_data['income'].value_counts(normalize=True) * 100,2)
})
income_dist_train

        Count  Percentage
income
<=50K   24720       75.92
>50K     7841       24.08

In [123]:
income_dist_test = pd.DataFrame({'Count': adult_test['income'].value_counts(),
                                 'Percentage': round(adult_test['income'].value_counts(normalize=True) * 100,2)
})
income_dist_test

        Count  Percentage
income
<=50K.  12435       76.38
>50K.    3846       23.62

### Cardinality Analysis

The number of unique values was examined for each feature.

Key observations:

- Numerical features such as fnlwgt, capital_gain, capital_loss, and hours_per_week have high cardinality.
- Categorical features such as workclass, occupation, education, race, and sex have relatively low cardinality.
- The train and test datasets show highly consistent cardinality patterns, indicating no significant schema drift.
- The target variable (income) contains two classes in both datasets.

In [128]:
unique_train = pd.DataFrame({'Unique Values': adult_data.nunique()}).sort_values(by='Unique Values',ascending=False)
unique_train

                Unique Values
fnlwgt                  21648
capital_gain              119
hours_per_week             94
capital_loss               92
age                        73
native_country             42
education                  16
education_num              16
occupation                 15
workclass                   9
marital_status              7
relationship                6
race                        5
sex                         2
income                      2

In [129]:
unique_test = pd.DataFrame({'Unique Values': adult_test.nunique()}).sort_values(by='Unique Values',ascending=False)
unique_test

                Unique Values
fnlwgt                  12787
capital_gain              113
hours_per_week             89
capital_loss               82
age                        73
native_country             41
education                  16
education_num              16
occupation                 15
workclass                   9
marital_status              7
relationship                6
race                        5
sex                         2
income                      2

### Numerical Feature Validation

Numerical features were examined using descriptive statistics.

Key observations:

- Age ranges from 17 to 90 years in both datasets.
- Education level encoding ranges from 1 to 16.
- Hours worked per week ranges from 1 to 99 hours, with a median of 40 hours.
- Capital gain and capital loss are highly skewed, with most observations equal to zero.
- The train and test datasets exhibit very similar statistical distributions.

No obvious numerical data quality issues were identified.

In [130]:
train_stats = adult_data.describe().T
train_stats

,count,mean,std,min,25%,50%,75%,max
age,32561.0,38.581647,13.640433,17.0,28.0,37.0,48.0,90.0
fnlwgt,32561.0,189778.366512,105549.977697,12285.0,117827.0,178356.0,237051.0,1484705.0
education_num,32561.0,10.080679,2.572720,1.0,9.0,10.0,12.0,16.0
capital_gain,32561.0,1077.648844,7385.292085,0.0,0.0,0.0,0.0,99999.0
capital_loss,32561.0,87.303830,402.960219,0.0,0.0,0.0,0.0,4356.0
hours_per_week,32561.0,40.437456,12.347429,1.0,40.0,40.0,45.0,99.0

In [131]:
test_stats = adult_test.describe().T
test_stats

,count,mean,std,min,25%,50%,75%,max
age,16281.0,38.767459,13.849187,17.0,28.0,37.0,48.0,90.0
fnlwgt,16281.0,189435.677784,105714.907671,13492.0,116736.0,177831.0,238384.0,1490400.0
education_num,16281.0,10.072907,2.567545,1.0,9.0,10.0,12.0,16.0
capital_gain,16281.0,1081.905104,7583.935968,0.0,0.0,0.0,0.0,99999.0
capital_loss,16281.0,87.899269,403.105286,0.0,0.0,0.0,0.0,3770.0
hours_per_week,16281.0,40.392236,12.479332,1.0,40.0,40.0,45.0,99.0

In [134]:
audit_train = pd.DataFrame({
    'Data Type': adult_data.dtypes,
    'Missing Count': (adult_data == '?').sum(),
    'Missing %': round(((adult_data == '?').sum() / len(adult_data)) * 100, 2),
    'Unique Values': adult_data.nunique()
})
audit_train

               Data Type  Missing Count  Missing %  Unique Values
age                int64              0       0.00             73
workclass         object           1836       5.64              9
fnlwgt             int64              0       0.00          21648
education         object              0       0.00             16
education_num      int64              0       0.00             16
marital_status    object              0       0.00              7
occupation        object           1843       5.66             15
relationship      object              0       0.00              6
race              object              0       0.00              5
sex               object              0       0.00              2
capital_gain       int64              0       0.00            119
capital_loss       int64              0       0.00             92
hours_per_week     int64              0       0.00             94
native_country    object            583       1.79             42
income            object              0       0.00              2

In [135]:
audit_test = pd.DataFrame({
    'Data Type': adult_test.dtypes,
    'Missing Count': (adult_test == '?').sum(),
    'Missing %': round(((adult_test == '?').sum() / len(adult_test)) * 100, 2),
    'Unique Values': adult_test.nunique()
})
audit_test

               Data Type  Missing Count  Missing %  Unique Values
age                int64              0       0.00             73
workclass         object            963       5.91              9
fnlwgt             int64              0       0.00          12787
education         object              0       0.00             16
education_num      int64              0       0.00             16
marital_status    object              0       0.00              7
occupation        object            966       5.93             15
relationship      object              0       0.00              6
race              object              0       0.00              5
sex               object              0       0.00              2
capital_gain       int64              0       0.00            113
capital_loss       int64              0       0.00             82
hours_per_week     int64              0       0.00             89
native_country    object            274       1.68             41
income            object              0       0.00              2

# Final Data Validation Summary

1. Both datasets were loaded successfully and contain the expected schema of 15 columns.

2. Train and test datasets have identical feature structures and data types.

3. Missing values are present in:
   - workclass
   - occupation
   - native_country

4. Missing values are encoded as '?' rather than null values.

5. Duplicate records exist but represent less than 0.1% of the data.

6. The target variable is moderately imbalanced:
   - Approximately 76% <=50K
   - Approximately 24% >50K

7. Numerical feature ranges appear valid and realistic.

8. No major schema inconsistencies or data quality issues were identified.

9. The dataset is suitable for CatBoost modeling and preprocessing will be performed in Notebook 03.